import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from './providers'
import localFont from 'next/font/local'
import { Suspense } from 'react'
import AuthenticatedHeader from '@/app/components/AuthenticatedHeader'
import HeaderSkeleton from '@/app/components/HeaderSkeleton'
import SplashScreen from '@/app/components/SplashScreen'

export const metadata: Metadata = {
  title: "m9",
  description: "노쇼 방지 예약 시스템",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "m9",
    // iOS Splash Screens - All iPhone & iPad sizes (generated by pwa-asset-generator)
    startupImage: [
      // iPhone 16 Pro Max (1320x2868)
      {
        url: "/splashscreens/apple-splash-1320-2868.jpg",
        media: "(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 16 Pro, 15 Pro Max, 14 Pro Max (1290x2796)
      {
        url: "/splashscreens/apple-splash-1290-2796.jpg",
        media: "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 16 Plus, 15 Plus, 14 Plus (1284x2778)
      {
        url: "/splashscreens/apple-splash-1284-2778.jpg",
        media: "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 16, 15 Pro, 14 Pro (1206x2622)
      {
        url: "/splashscreens/apple-splash-1206-2622.jpg",
        media: "(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 15, 14 Pro (1179x2556)
      {
        url: "/splashscreens/apple-splash-1179-2556.jpg",
        media: "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 14, 13, 13 Pro, 12, 12 Pro (1170x2532)
      {
        url: "/splashscreens/apple-splash-1170-2532.jpg",
        media: "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 13 mini, 12 mini, 11 Pro, XS, X (1125x2436)
      {
        url: "/splashscreens/apple-splash-1125-2436.jpg",
        media: "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 11 Pro Max, XS Max (1242x2688)
      {
        url: "/splashscreens/apple-splash-1242-2688.jpg",
        media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone 11, XR (828x1792)
      {
        url: "/splashscreens/apple-splash-828-1792.jpg",
        media: "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPhone 8 Plus, 7 Plus, 6s Plus (1242x2208)
      {
        url: "/splashscreens/apple-splash-1242-2208.jpg",
        media: "(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)",
      },
      // iPhone SE (3rd/2nd gen), 8, 7, 6s (750x1334)
      {
        url: "/splashscreens/apple-splash-750-1334.jpg",
        media: "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPhone SE (1st gen), 5s, 5c (640x1136)
      {
        url: "/splashscreens/apple-splash-640-1136.jpg",
        media: "(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad Pro 12.9" (2048x2732)
      {
        url: "/splashscreens/apple-splash-2048-2732.jpg",
        media: "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad Pro 11" (1668x2388)
      {
        url: "/splashscreens/apple-splash-1668-2388.jpg",
        media: "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad Pro 10.5", Air 3rd gen (1668x2224)
      {
        url: "/splashscreens/apple-splash-1668-2224.jpg",
        media: "(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad Air 5/4, 10th gen (1640x2360)
      {
        url: "/splashscreens/apple-splash-1640-2360.jpg",
        media: "(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad 9th/8th/7th gen (1620x2160)
      {
        url: "/splashscreens/apple-splash-1620-2160.jpg",
        media: "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad mini 6th gen (1488x2266)
      {
        url: "/splashscreens/apple-splash-1488-2266.jpg",
        media: "(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
      // iPad 6th/5th gen, mini 5th gen (1536x2048)
      {
        url: "/splashscreens/apple-splash-1536-2048.jpg",
        media: "(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)",
      },
    ],
  },
  formatDetection: {
    telephone: false,
  },
  // Explicit setting for iOS splash screen (workaround for Next.js 15)
  other: {
    "apple-mobile-web-app-capable": "yes",
    "mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  themeColor: "#0f766e",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

const pretendard = localFont({
  src: '../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" suppressHydrationWarning className={pretendard.variable} style={{ backgroundColor: '#f8fafc' }}>
      <body className={pretendard.className} style={{ backgroundColor: '#f8fafc' }}>
        <Providers>
          <SplashScreen />
          <Suspense fallback={<HeaderSkeleton />}>
            <AuthenticatedHeader />
          </Suspense>
          <main className="page-container">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
